global:
  scrape_interval:     60s
  evaluation_interval: 60s
  external_labels:
    localization_name : ${localization_name}
scrape_configs:
  - job_name: 'prometheus'
    honor_labels: true
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'groviepi-exporter'
    honor_labels: true
    static_configs:
      - targets: ['grovepi_exporter:8081']
  - job_name: 'nodeexporter'
    honor_labels: true
    scrape_interval: 10s
    static_configs:
      - targets: ['node_exporter:9100']

rule_files:
    - "alerts/*.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
