{
 "title": "groviepi-exporter",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "light",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_light" }
   ]
  },
  {
   "title": "Loudless",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_sound" }
   ]
  },
  { "title": "hcho_sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "ppm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_hcho_ppm" }
   ]
  },
  {
   "title": "sensor_value",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_hcho_sensor_value" }
   ]
  },
  {
   "title": "Rs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_hcho_rs" }
   ]
  },
  {
   "title": "Sensitivity Curve",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(grovepi_hcho_rs/grovepi_hcho_r0)/grovepi_hcho_ppm"
    }
   ]
  },
  { "title": "dht_sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_dht_temperature" }
   ]
  },
  {
   "title": "humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_dht_humidity" }
   ]
  }
 ]
}